name: Build PBR

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '2 0/12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN }}
